#!/bin/sh

# Convenience script to start the SmartDoor adapter.

JAVA=/usr/bin/java
VERSION=0.1.1
JAR_FILE=smartdoor-adapter-${VERSION}-jar-with-dependencies.jar

HOSTNAME=$(hostname)
NAME=smartdoor-adapter-java@${HOSTNAME}
URL=
TOKEN=

$JAVA -jar ./target/${JAR_FILE} $NAME $URL $TOKEN
